# Generated by Django 2.2.6 on 2019-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Parceiro', max_length=50, verbose_name='Nome')),
                ('imagem', models.ImageField(help_text='Selecione uma Foto', upload_to='adocao', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
