# Generated by Django 2.2.6 on 2019-11-11 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Descrição Parceiro'),
            preserve_default=False,
        ),
    ]
