# Generated by Django 2.2.6 on 2019-11-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_parceiros_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
    ]
