# Generated by Django 2.2.6 on 2019-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_parceiros_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo do Slider', max_length=50, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição Parceiro')),
                ('imagem', models.ImageField(help_text='Selecione uma Foto de Boa Qualidade', upload_to='adocao', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
