# Generated by Django 2.2.6 on 2019-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterianrioLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Clinica', max_length=50, verbose_name='Nome')),
                ('imagem', models.ImageField(help_text='Selecione uma Foto de Boa Qualidade', upload_to='veterianioParceiro', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagem',
            field=models.ImageField(help_text='Selecione uma Foto de Boa Qualidade', upload_to='slide', verbose_name='Imagem'),
        ),
    ]
