# Generated by Django 2.2.6 on 2019-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191113_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterianriologo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='imagem',
            field=models.ImageField(height_field=370, help_text='Selecione uma Foto', upload_to='adocao', verbose_name='Foto', width_field=240),
        ),
    ]
