# Generated by Django 2.2.6 on 2019-11-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191113_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parceiros',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='imagem',
            field=models.ImageField(height_field='height_field', help_text='Selecione uma Foto', upload_to='adocao', verbose_name='Foto', width_field='width_field'),
        ),
    ]
