# Generated by Django 2.2.6 on 2019-11-14 04:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191113_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloSite', models.CharField(help_text='Titulo da Aba', max_length=50, verbose_name='Titulo do Site')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['tituloSite'],
            },
        ),
    ]
