# Generated by Django 2.2.6 on 2019-11-14 12:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191114_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR'),
        ),
    ]
