# Generated by Django 2.2.6 on 2019-11-14 18:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_parceiros_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoessite',
            options={'ordering': ['tituloSite'], 'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='parceiros',
            options={'ordering': ['nome'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['titulo'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='veterianriologo',
            options={'ordering': ['nome'], 'verbose_name': 'Veterianrio Logo', 'verbose_name_plural': 'Veterianrio Logos'},
        ),
        migrations.AddField(
            model_name='configuracoessite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='configuracoessite',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='configuracoessite',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR'),
        ),
    ]
