# Generated by Django 2.2.6 on 2019-11-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191114_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoessite',
            name='sobre',
            field=models.TextField(blank=True, null=True, verbose_name='Uma Breve Descrição'),
        ),
    ]
