# Generated by Django 2.2.6 on 2019-11-24 19:46

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Exemplo TóTó', max_length=50, null=True, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('fotoPerfil', sorl.thumbnail.fields.ImageField(upload_to='adocao')),
                ('atotado', models.BooleanField(default=False, verbose_name='Adotado?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Cadastro Pet',
                'verbose_name_plural': 'Cadastros Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Categoria', max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Categoria Pet',
                'verbose_name_plural': 'Categorias Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='PetImagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', sorl.thumbnail.fields.ImageField(upload_to='adocao')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pet.CadastroPet')),
            ],
        ),
        migrations.AddField(
            model_name='cadastropet',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.CategoriaPet'),
        ),
        migrations.AddField(
            model_name='cadastropet',
            name='Especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Especie'),
        ),
    ]
