# Generated by Django 2.2.6 on 2019-11-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimagens',
            old_name='nome',
            new_name='pet',
        ),
    ]
