# Generated by Django 2.2.6 on 2019-11-24 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20191124_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropet',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, help_text='Exemplo TóTó', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
