# Generated by Django 2.2.6 on 2019-11-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20191124_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimagens',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_imagens', to='pet.CadastroPet'),
        ),
    ]
